### ISSUE TITLE
truffle test not pass

### ISSUE THREAD

**Issue by YingQm** [cosmos/peggy#154]
my version:
Truffle v5.1.14-nodeLTS.0 (core: 5.1.13)
Solidity v0.5.16 (solc-js)
Node v12.16.0
Web3.js v1.2.1

use Ganache test the contract, return test did not pass

**Comment by YingQm** [comment]
46 passing (28s)
  16 failing

  1) Contract: BridgeBank
       Bridge token minting (for locked Cosmos assets)
         "before each" hook for "should mint bridge tokens upon the successful processing of a burn prophecy claim":
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:319:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should unlock Ethereum upon the processing of a burn prophecy:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:592:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should unlock and transfer ERC20 tokens upon the processing of a burn prophecy:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:659:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  4) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should allow locked funds to be unlocked incrementally by successive burn prophecies:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:726:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  5) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should not allow burn prophecies to be processed twice:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:870:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  6) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should only allow locked funds to be unlocked, even if the contract holds surplus funds:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:925:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  7) Contract: Oracle
       Creation of oracle claims
         should allow validators to make OracleClaims with their own signatures:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..'
  

  8) Contract: Oracle
       Creation of oracle claims
         should not allow validators to make duplicate OracleClaims:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..'
  

  9) Contract: Oracle
       Creation of oracle claims
         should emit an event containing the new OracleClaim's information:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:275:42)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  10) Contract: Oracle
       Prophecy processing
         should not process the prophecy if signed power does not pass the required threshold power:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:389:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  11) Contract: Oracle
       Prophecy processing
         should allow for the processing of prophecies:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:405:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  12) Contract: Oracle
       Prophecy processing
         should allow non-unanimous consensus if signed power passes threshold:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:439:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  13) Contract: Oracle
       Prophecy processing
         should not allow a prophecy to be processed twice:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:472:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  14) Contract: Oracle
       Prophecy processing
         should emit an event upon successful prophecy processing:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:507:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  15) Contract: Valset
       Signature verification
         should correctly validate signatures:

      AssertionError: expected '0xf121d6E2b49b121B31ad93A8f388469f7525eBbE' to equal '0x7B8f3E3479Ec938c8959cAD07327Ef038b2127C1'
      + expected - actual

      -0xf121d6E2b49b121B31ad93A8f388469f7525eBbE
      +0x7B8f3E3479Ec938c8959cAD07327Ef038b2127C1
      
      at Context.<anonymous> (test/test_valset.js:572:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  16) Contract: Valset
       Signature verification
         should not validate signatures on a different hashed message:

      AssertionError: expected '0x55532D40e64188E5F8DD3ca37FC61Cb7A93b38F3' to equal '0x0000000000000000000000000000000000000000'
      + expected - actual

      -0x55532D40e64188E5F8DD3ca37FC61Cb7A93b38F3
      +0x0000000000000000000000000000000000000000
      
      at Context.<anonymous> (test/test_valset.js:590:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by YingQm** [comment]
` 46 passing (28s)
  16 failing

  1) Contract: BridgeBank
       Bridge token minting (for locked Cosmos assets)
         "before each" hook for "should mint bridge tokens upon the successful processing of a burn prophecy claim":
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:319:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should unlock Ethereum upon the processing of a burn prophecy:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:592:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should unlock and transfer ERC20 tokens upon the processing of a burn prophecy:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:659:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  4) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should allow locked funds to be unlocked incrementally by successive burn prophecies:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:726:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  5) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should not allow burn prophecies to be processed twice:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:870:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  6) Contract: BridgeBank
       Ethereum/ERC20 token unlocking (for burned Cosmos assets)
         should only allow locked funds to be unlocked, even if the contract holds surplus funds:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_bridgeBank.js:925:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  7) Contract: Oracle
       Creation of oracle claims
         should allow validators to make OracleClaims with their own signatures:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..'
  

  8) Contract: Oracle
       Creation of oracle claims
         should not allow validators to make duplicate OracleClaims:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..'
  

  9) Contract: Oracle
       Creation of oracle claims
         should emit an event containing the new OracleClaim's information:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:275:42)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  10) Contract: Oracle
       Prophecy processing
         should not process the prophecy if signed power does not pass the required threshold power:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:389:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  11) Contract: Oracle
       Prophecy processing
         should allow for the processing of prophecies:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:405:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  12) Contract: Oracle
       Prophecy processing
         should allow non-unanimous consensus if signed power passes threshold:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:439:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  13) Contract: Oracle
       Prophecy processing
         should not allow a prophecy to be processed twice:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:472:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  14) Contract: Oracle
       Prophecy processing
         should emit an event upon successful prophecy processing:
     Error: Returned error: VM Exception while processing transaction: revert Invalid message signature. -- Reason given: Invalid message signature..
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.newOracleClaim (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at Context.<anonymous> (test/test_oracle.js:507:25)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  15) Contract: Valset
       Signature verification
         should correctly validate signatures:

      AssertionError: expected '0xf121d6E2b49b121B31ad93A8f388469f7525eBbE' to equal '0x7B8f3E3479Ec938c8959cAD07327Ef038b2127C1'
      + expected - actual

      -0xf121d6E2b49b121B31ad93A8f388469f7525eBbE
      +0x7B8f3E3479Ec938c8959cAD07327Ef038b2127C1
      
      at Context.<anonymous> (test/test_valset.js:572:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  16) Contract: Valset
       Signature verification
         should not validate signatures on a different hashed message:

      AssertionError: expected '0x55532D40e64188E5F8DD3ca37FC61Cb7A93b38F3' to equal '0x0000000000000000000000000000000000000000'
      + expected - actual

      -0x55532D40e64188E5F8DD3ca37FC61Cb7A93b38F3
      +0x0000000000000000000000000000000000000000
      
      at Context.<anonymous> (test/test_valset.js:590:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

**Comment by YingQm** [comment]
In file CosmosBridge.sol, Burn = 1
`
enum ClaimType {
        Unsupported,
        Burn,
        Lock
}
`

but in file test_cosmosBridge.js, CLAIM_TYPE_BURN  = 0
`
const CLAIM_TYPE_BURN = 0;
const CLAIM_TYPE_LOCK = 1;
`

**Comment by denalimarsh** [comment]
@YingQm thanks for opening this issue.

The contract test suite is currently out of date. I'm working on an upgrade to the contracts that will include the relevant fixes.
