### ISSUE TITLE
peggy:lock doesn't parse large numbers correctly

### ISSUE THREAD

**Issue by okwme** [cosmos/peggy#174]
When trying to use the following command:
```
> yarn peggy:lock $(ebcli keys show testuser -a) 0x345cA3e014Aaf5dcA488057592ee47305D9B3e10 10000000000000000000                 
```
I get the following error:
```
{
  error: Error: invalid number value (arg="_amount", coderType="uint256", value=10000000000000000000)
      at Object.throwError (/home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/ethers/utils/errors.js:68:17)
      at CoderNumber.encode (/home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/ethers/utils/abi-coder.js:353:20)
      at /home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (/home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (/home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (/home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (/home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/web3-eth-abi/src/index.js:96:27)
      at /home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (/home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/web3-eth-contract/src/index.js:425:12)
      at /home/billyrennekamp/GitHub.com/denalimarsh/peggy/node_modules/truffle-contract/lib/execute.js:169:42
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    reason: 'invalid number value',
    code: 'INVALID_ARGUMENT',
    arg: '_amount',
    coderType: 'uint256',
    value: 10000000000000000000
  }
```
But when I use a smaller number like:
```
> yarn peggy:lock $(ebcli keys show testuser -a) 0x345cA3e014Aaf5dcA488057592ee47305D9B3e10 1000000000000000 
```
I succeed. I think this has to do with the limits of javascript in parsing and printing in scientific notation. BigNumber.js or an equivalent library should always be used with dealing with ethereum integers.

**Comment by denalimarsh** [comment]
fixed in https://github.com/cosmos/peggy/pull/163/commits/2fb8ce803fc9a7c2fe99bf53c2b3db7a568c5c67
