### ISSUE TITLE
Unable to Start the Relayer Process !!!

### ISSUE THREAD

**Issue by SudeshGagare** [cosmos/peggy#191]
cosmos@ubuntu:/go/src/github.com/cosmos/peggy/testnet-contracts$ ebrelayer init tcp://localhost:26657 ws://localhost:7545/ 0x30753E4A8aad7F8597332E813735Def5dD395028 validator --chain-id==peggy
2020/04/27 21:02:31 invalid hex string
cosmos@ubuntu:/go/src/github.com/cosmos/peggy/testnet-contracts$

**Comment by denalimarsh** [comment]
Hello @SudeshGagare 

Have you set your environment variables in `.env` and `testnet-contracts/.env`? They should be nearly identical to the environment variables in `.env.example` and `testnet-contracts/.env.example`.

**Comment by SudeshGagare** [comment]
Yes, Thanks a lot!!! Resolved the issue.
But, now a new issue is arising while starting local Ethereum blockchain

****cosmos@ubuntu:~/go/src/github.com/cosmos/peggy/testnet-contracts$ yarn migrate
yarn run v1.19.1
$ truffle migrate --reset
Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)**
    at spawn (child_process.js:538:9)
    at Object.fork (child_process.js:113:10)**
    at Object.send (/home/cosmos/go/src/github.com/cosmos/peggy/node_modules/truffle/build/webpack:/packages/core/lib/services/analytics/index.js:12:1)
    at Command.run (/home/cosmos/go/src/github.com/cosmos/peggy/node_modules/truffle/build/webpack:/packages/core/lib/command.js:137:1)
    at Object.<anonymous> (/home/cosmos/go/src/github.com/cosmos/peggy/node_modules/truffle/build/webpack:/packages/core/cli.js:52:1)
    at __webpack_require__ (/home/cosmos/go/src/github.com/cosmos/peggy/node_modules/truffle/build/webpack:/webpack/bootstrap 51589e08a62c87b5b792:19:1)
    at /home/cosmos/go/src/github.com/cosmos/peggy/node_modules/truffle/build/webpack:/webpack/bootstrap 51589e08a62c87b5b792:62:1
    at Object.<anonymous> (/home/cosmos/go/src/github.com/cosmos/peggy/node_modules/truffle/build/cli.bundled.js:68:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Truffle v5.1.19 (core: 5.1.19)
Node v10.15.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
